### ISSUE TITLE
Particle Filtering is not yet implemented in Spandex_Stack

### ISSUE THREAD

**Issue by jtrueb** [derinsevenler/Spandex#23]
The current implementation of spandex_stack returns many potential particle locations that are not the result of surface bound NPs.  The simplest way to filter down these false positives is to compare potential particle locations with a previously generated template, and kick out signals that fall below some correlation threshold.

Successful implementation will require a few different components, as follows.

Associated Matlab Scripts:  Numerical simulation software will need to be adapted to output templates in a file format compatible with micromanager.  Current format is in a .mat file, but future versions should output a .tif with extra metadata, which can be saved locally and accessed by Spandex_Stack.

Interface: User will need to select be able to view information about which templates are available, and select the appropriate file for the given optical system.

Filtering Subroutine: Should accept the list of XY locations generated by initial detection and correlate a local crop of each position with the saved template.  Low scoring locations should be removed from the list.

**Comment by derinsevenler** [comment]
You should check out Spandex_Flicker, which is a separate but similar plugin meant for flickering particles.

**Comment by derinsevenler** [comment]
Check out this example plugin that uses a PSF template as an image - we could do something similar. 

https://imagej.net/Deconvolution#Constrained_Iterative_Deconvolution

**Comment by derinsevenler** [comment]
Since some particles flicker, and others don't, our current approach is to simply acquire a z-stack and use spandex_stack. Spandex_flicker is no longer recommended.
