### ISSUE TITLE
Spandex_stack: NIR background is not 0

### ISSUE THREAD

**Issue by derinsevenler** [derinsevenler/Spandex#3]
The threshold background should be approximately 0 but it's not right now. This could be due to shot noise, or the image gradient changing with z position - likely both.

**Comment by cllyrdkl** [comment]
We can implement local NIR subtraction for a specific number of pixel (e.g 10x10), kind of mean average. Similarly, we can implement sift as in the single particle detection in matlab.

**Comment by jtrueb** [comment]
We have used sift extensively in the past, but it ends up creating a lot
more problems than it solves.  We don't need a scale invariant approach
when we are looking for particles with a single consistent scale.

Jake

**Comment by derinsevenler** [comment]
This was addressed about a month ago, in Spandex_Stack.
