### ISSUE TITLE
No implementation of Spandex_single

### ISSUE THREAD

**Issue by derinsevenler** [derinsevenler/Spandex#6]
Spandex_single would be a weaker version of Spandex_stack, that works on a single image. This would be useful for high-speed acquisitions.

**Comment by JosephGreene** [comment]
I'll work on developing Spandex_Single as an introductory step for learning how ImageJ/Java Plugins work.

**Comment by JosephGreene** [comment]
Spandex_Single has been finalized. I will commit my branch after I implement the corresponding realtimesingle acquisition script
