### ISSUE TITLE
Spandex_stack: does not return particle data

### ISSUE THREAD

**Issue by derinsevenler** [derinsevenler/Spandex#9]
We would like to have access to statistics such as NIR (normalized intensity range) and PPS (peak plane separation), so we can perform sizing and characterization as well.

**Comment by jtrueb** [comment]
I think we should simply include these measurements as addition columns with the XY location text file.

**Comment by rezakheradmand** [comment]
As I understood well, we just need to define the maximum value in the codes. If the maximum position changes with time we can follow it also with this method.
